_target_: src.methods.SemanticEntropy
model_name: ${model_name} 
dtype: float16 
device: cuda
cache_dir: cache/semantic_entropy_8_09
generated_responses_dir: cache/generated_responses_8_09_5
num_return_sequences: 5
temperature: 1.0
max_new_tokens: 256
