prompt = {
    "SQuAD": """I need your help to annotate hallucinations in a Question Answering (QA) task. Hallucinations in this context refer to instances where the generated answers contain factually incorrect or irrelevant information that is not supported by the provided context or common knowledge.

Instructions:

Identify Hallucinations: Carefully read the context, question, correct answer to the question and the answer generated by an LLM. Determine if the answer generated by an LLM contains any hallucinations.
Response options:
    - "Yes": If the answer contains hallucinations (answer contradicts or is not supported by the context and the general knowledge)
    - "No": If the answer does not contain hallucinations (all claims are supported by the context)
    - "N/A": If you cannot determine or the answer is generally correct but not explicitly supported by the context

Positive Example (Answers that contradict the context and are factually incorrect):
Context: The Eiffel Tower is an iron lattice tower situated on the Champ de Mars in the 7th arrondissement of Paris. It was named after the engineer Gustave Eiffel, whose company designed and built the tower.
Question: Who designed the Eiffel Tower?
Correct answer(s): ['Gustave Eiffel', 'Eiffel']
LLM-generated answer: The Eiffel Tower was designed by Mario Piuso and constructed by his company.
Annotation: Yes

Positive Example (Answers that are not supported by the context and are factually incorrect):
Context: The Eiffel Tower is an iron lattice tower situated on the Champ de Mars in the 7th arrondissement of Paris. It was named after the engineer Gustave Eiffel, whose company designed and built the tower.
Question: When was the Eiffel Tower built?
Correct answer(s): ['The answer is not mentioned in the given context.']
LLM-generated answer: The Eiffel Tower was built in the 18th century.
Annotation: Yes

Negative Example (No Hallucinations):
Context: The Eiffel Tower is an iron lattice tower situated on the Champ de Mars in the 7th arrondissement of Paris. It was named after the engineer Gustave Eiffel, whose company designed and built the tower.
Question: Who designed the Eiffel Tower?
Correct answer(s): ['Gustave Eiffel', 'Eiffel']
LLM-generated answer: The Eiffel Tower was designed by Gustave Eiffel.
Annotation: No

Not assigned Example (Answers that are not supported by the context but are correct):
Context: The Eiffel Tower is an iron lattice tower situated on the Champ de Mars in the 7th arrondissement of Paris. It was named after the engineer Gustave Eiffel, whose company designed and built the tower.
Question: When was the Eiffel Tower built?
Correct answer(s): ['The answer is not mentioned in the given context.']
LLM-generated answer: The Eiffel Tower was built in the 19th century.
Annotation: N/A

If you cannot decide if the generated answer contains hallucinations, write "N/A" as the answer. The answer you give MUST be ONLY "Yes", "No", or "N/A"; do NOT give ANY extra explanation.\n\n""",
"CoQA": """I would like you to act as a hallucination annotator in an answer. I will provide a reference text, a question referring to this text, and a model-generated answer to this question. You will judge whether the given model-generated answer contains hallucinations.
The specific requirements are as follows:
1. If the reference text supports the answer, please write: "No".
2. If the answer contradicts the reference text, please write: "Yes".
3. If the reference text does not support the answer, please write: "Yes".
4. If you cannot decide whether or not the generated answer contains hallucinations, please write "N/A".

Here are a few examples to illustrate this task:

Example 1

#Context#: The Great Barrier Reef is the world's largest coral reef system, located in the Coral Sea, off the coast of Australia. It is composed of more than 2,900 individual reefs and 900 islands, spanning over 2,300 kilometers. The reef system is home to a vast array of marine life, including over 1,500 species of fish, 600 species of coral, and many other creatures. Q: Where is the Great Barrier Reef located? A: Off the coast of Australia. Q: How many individual reefs make up the Great Barrier Reef? A: More than 2,900. Q: What is the approximate length of the Great Barrier Reef? A: Over 2,300 kilometers.
#Question#: Is the Great Barrier Reef located in the Coral Sea?
#Answer#: Yes.
#Hallucination#: No

Example 2

#Context#: The human brain is a complex organ that serves as the center of the nervous system. It is responsible for controlling various bodily functions, such as movement, sensation, and cognition. The brain is composed of billions of neurons, which communicate with each other through electrical and chemical signals. Q: What is the primary function of the brain? A: To control various bodily functions. Q: How many neurons are in the brain? A: Billions. Q: What type of signals do neurons use to communicate? A: Electrical and chemical.
#Question#: Does the brain use electrical and chemical signals to communicate?
#Answer#: No, it uses only electrical signals to communicate.
#Hallucination#: Yes

Example 3

#Context#: The famous painting "The Starry Night" was created in 1889. The painting is known for its swirling clouds and stars set against a dark blue sky. Q: What year was "The Starry Night" created? A: 1889. Q: What is the painting's most distinctive feature? A: Swirling clouds and stars.
#Question#: Was "The Starry Night" painted by Leonardo da Vinci?
#Answer#: Yes.
#Hallucination#: Yes


Now, given a new context, question, and answer, your task is to determine whether the answer is hallucinated or not. Do NOT give any extra explanations.\n\n""",
    "XSum": """Please annotate potential hallucinations in model-generated summaries.

Task: I will provide a reference text and a model-generated summary. You need to judge whether the summary contains hallucinations.

Definition of Hallucinations:
- Claims that CONTRADICT the reference text
- Claims that are NOT SUPPORTED by the reference text
- Factual errors or fabrications not present in the reference text
- Information that cannot be inferred from the reference text

Response Guidelines:
- "Yes": The summary contains hallucinations (contradictions or unsupported claims)
- "No": The summary accurately reflects the reference text with no hallucinations
- "N/A": You cannot determine if hallucinations are present

Examples:

Reference Text: The company reported quarterly revenue of $5.2 billion, up 15% from the previous year. Net income reached $800 million. The CEO announced plans to expand into three new markets.
Generated summary: The company's revenue was $5.2 billion with $800 million profit. They will enter new markets.
Annotation: No

Reference Text: The company reported quarterly revenue of $5.2 billion, up 15% from the previous year. Net income reached $800 million.
Generated summary: The company's revenue grew 25% this quarter to $6.1 billion.
Annotation: Yes

Reference Text: The company reported strong quarterly results with significant growth in key markets.
Generated summary: The company exceeded analyst expectations with record-breaking performance.
Annotation: Yes

Important: Your response must be EXACTLY one of these three options: "Yes", "No", or "N/A" with no additional text or explanation.\n\n""",
    }

dataset = "CoQA"

annotation_prompt = prompt[dataset]
if dataset == "CoQA":
    query_str = f"#Context#: {row['context']}\n#Question#: {row['question']}\n#Answer#: {row['generated_answer']}\n#Hallucination#:"
elif dataset == "SQuAD":
    tmp_answer = row["answers"]
    query_str = f"Context: {row['context']}\nQuestion: {row['question']}\nCorrect answer(s): {tmp_answer}\nLLM-generated answer: {row['generated_answer']}\nAnnotation:"
elif dataset == "XSum":
    query_str = f"Reference Text: {row['document']}\nGenerated summary: {row['generated_summary']}\nAnnotation:"
query_text = annotation_prompt + query_str
